I had problems with connecting to the UNESCO data APT with pandaSDMX, see the [related SO discussion](https://stackoverflow.com/questions/48605898/unesco-sdmx-api-data-into-pandas-dataframe).
